import { arabicPlural } from '../plural';
import type { Catalogue } from '../shape';

export const LOOKUPS = {
  hint: 'مخفية: لا تظهر في الفلاتر والنماذج. المساحات المرتبطة بها تبقى كما هي. الترتيب هنا هو ترتيب الظهور.',
  governorates: {
    title: 'المحافظات والمناطق',
    add: 'إضافة محافظة',
    areaCount: ({ count }: { count: number }) =>
      arabicPlural(count, {
        zero: 'لا مناطق',
        one: 'منطقة واحدة',
        two: 'منطقتان',
        few: `${String(count)} مناطق`,
        many: `${String(count)} منطقة`,
        other: `${String(count)} منطقة`,
      }),
    empty: 'لا محافظات بعد',
    emptyHint: 'أضف أول محافظة، ثم مناطقها.',
    loadFailed: 'تعذّر تحميل المحافظات',
  },
  areas: {
    add: 'إضافة منطقة',
  },
  amenities: {
    title: 'المرافق',
    description:
      '«في الفلاتر» متوقف لما يتوفر في كل المساحات تقريبًا، لأنه لا يميّز مساحة عن أخرى.',
    add: 'إضافة مرفق',
    empty: 'لا مرافق بعد',
    emptyHint: 'أضف أول مرفق.',
    loadFailed: 'تعذّر تحميل المرافق',
    row: {
      notFiltered: 'ليس في الفلاتر',
      inactive: 'غير نشط',
      inFilters: 'في الفلاتر',
      inFiltersName: ({ name }: { name: string }) => `في الفلاتر: ${name}`,
      active: 'نشط',
      activeName: ({ name }: { name: string }) => `نشط: ${name}`,
    },
  },
  row: {
    hidden: 'مخفية',
    shown: ({ name }: { name: string }) => `ظاهرة: ${name}`,
    moveUp: ({ name }: { name: string }) => `تحريك لأعلى: ${name}`,
    moveDown: ({ name }: { name: string }) => `تحريك لأسفل: ${name}`,
    edit: 'تعديل',
    editName: ({ name }: { name: string }) => `تعديل: ${name}`,
  },
  failure: {
    title: 'لم يُحفظ التغيير',
    orderChanged: 'تغيّر الترتيب في الأثناء، وعُرض الترتيب الجديد. حاول مرة أخرى.',
  },
  sheet: {
    addGovernorate: 'إضافة محافظة',
    editGovernorate: 'تعديل محافظة',
    addArea: 'إضافة منطقة',
    editArea: 'تعديل منطقة',
    addAmenity: 'إضافة مرفق',
    editAmenity: 'تعديل مرفق',
    icon: 'الأيقونة',
    inFilters: 'في الفلاتر',
    inFiltersHint: 'يظهر ضمن فلاتر دليل المساحات.',
    amenityActive: 'نشط',
    amenityActiveHint: 'غير نشط: لا يظهر في النماذج والفلاتر، وتحتفظ به المساحات التي لديها.',
    nameAr: 'الاسم بالعربية',
    nameEn: 'الاسم بالإنجليزية',
    active: 'نشطة',
    activeHint: 'مخفية: لا تظهر في الفلاتر والنماذج.',
    save: 'حفظ',
    close: 'إغلاق',
    saveFailed: 'تعذّر الحفظ',
    fieldErrors: {
      nameAr: { too_short: 'أدخل الاسم بالعربية' },
      nameEn: {
        too_short: 'أدخل الاسم بالإنجليزية',
        invalid_format: 'استخدم حروفًا لاتينية أو أرقامًا في الاسم الإنجليزي',
      },
      icon: { invalid_choice: 'اختر أيقونة' },
      governorateTaken: 'توجد محافظة أخرى بهذا الاسم العربي',
      areaTaken: 'توجد منطقة أخرى في هذه المحافظة بهذا الاسم العربي',
      amenityTaken: 'يوجد مرفق آخر بهذا الاسم الإنجليزي',
    },
  },
  icons: {
    wifi: 'واي فاي',
    zap: 'برق',
    sun: 'شمس',
    'plug-zap': 'قابس كهرباء',
    coffee: 'فنجان قهوة',
    users: 'أشخاص',
    presentation: 'لوح عرض',
    'graduation-cap': 'قبعة تخرّج',
  },
} satisfies Catalogue['lookups'];
