import type { Catalogue } from '../shape';

export const SPACE_LINKS = {
  switchSpace: ({ name }: { name: string }) => `تبديل المساحة: ${name}`,
  yourSpaces: 'مساحاتك',
  chooseSpace: 'اختر مساحة',
  loadFailed: 'تعذّر تحميل مساحاتك',
  adminList: {
    label: 'المساحات',
    search: 'بحث',
    searchPlaceholder: 'اسم المساحة',
    place: 'المحافظة / المنطقة',
    status: 'الحالة',
    allStatuses: 'كل الحالات',
    states: {
      verified: 'موثّقة',
      unverified: 'غير موثّقة',
      hidden: 'مخفية',
    },
    staleOnly: 'بيانات قديمة فقط',
    filters: 'الفلاتر',
    filtersApplied: ({ count }: { count: number }) => `الفلاتر، المطبّق منها: ${String(count)}`,
    clearFilters: 'مسح الفلاتر',
    close: 'إغلاق',
    columns: {
      space: 'المساحة',
      area: 'المنطقة',
      status: 'الحالة',
      owner: 'صاحب المساحة',
      freshness: 'الحداثة',
      lastUpdate: 'آخر تحديث',
      actions: 'إجراءات',
    },
    owners: ({ owners }: { owners: string }) => `صاحب المساحة: ${owners}`,
    noOwner: 'بلا صاحب مساحة',
    upToDate: 'محدّثة',
    stale: ({ groups }: { groups: string }) => `قديمة: ${groups}`,
    missing: ({ groups }: { groups: string }) => `غير مُدخلة: ${groups}`,
    groups: {
      profile: 'البيانات الأساسية',
      hours: 'ساعات العمل',
      prices: 'الأسعار',
      amenities: 'المرافق',
      contacts: 'التواصل',
    },
    separator: '، ',
    count: ({ count }: { count: number }) => `عدد المساحات: ${String(count)}`,
    empty: 'لا توجد مساحات بعد',
    emptyHint: 'تظهر المساحات هنا بعد إضافتها.',
    noMatch: 'لا توجد مساحات تطابق الفلاتر',
    loadFailed: 'تعذّر تحميل المساحات',
    pagination: {
      label: 'صفحات قائمة المساحات',
      previous: 'السابق',
      next: 'التالي',
      page: ({ page }: { page: number }) => `الصفحة ${String(page)}`,
      summary: ({ page, total }: { page: number; total: number }) =>
        `الصفحة ${String(page)} من ${String(total)}`,
      more: 'صفحات أخرى',
    },
  },
} satisfies Catalogue['spaceLinks'];
