import type { Catalogue } from '../shape';

export const TERMS = {
  space: 'مساحة',
  verifiedSpace: 'مساحة موثّقة',
  unverifiedSpace: 'مساحة غير موثّقة',
  owner: 'صاحب المساحة',
  spaceManagerLink: 'ربط الإدارة',
  reception: 'الاستقبال',
  frontDesk: 'مكتب الاستقبال',
  customer: 'زبون',
  visit: 'زيارة',
  subscription: 'اشتراك',
  package: 'باقة',
  customSubscription: 'اشتراك مخصّص',
  subscriptionStatus: 'حالة الاشتراك',
  subscriptionStatuses: {
    active: 'نشط',
    endingSoon: 'ينتهي قريبًا',
    expired: 'منتهٍ',
  },
  payment: 'دفعة',
  amountDue: 'المستحق',
  balance: 'المتبقي',
  credit: 'له رصيد',
  paymentStatus: 'حالة الدفع',
  paymentStatuses: {
    paid: 'مدفوع',
    partlyPaid: 'مدفوع جزئيًا',
    unpaid: 'غير مدفوع',
  },
  voidPayment: 'إلغاء دفعة',
  shift: 'وردية',
  checkIn: 'تسجيل حضور',
  openCheckIn: 'حضور مفتوح',
  autoCheckOut: 'خروج تلقائي',
  capacity: 'السعة',
  liveStatus: 'الحالة المباشرة',
  liveStatuses: {
    available: 'متاح',
    full: 'ممتلئ',
    closedNow: 'مغلق الآن',
  },
  manualStateOverride: 'ضبط الحالة يدويًا',
  occupancy: 'الإشغال',
  announcement: 'إعلان',
  dataReport: 'بلاغ',
  stale: 'قد تكون قديمة',
  governorate: 'محافظة',
  area: 'منطقة',
  lookup: 'قائمة ثابتة',
  auditLog: 'سجل التدقيق',
} satisfies Catalogue['terms'];
