/** The canonical vocabulary (docs/project/glossary.md), for labels, headings and statuses. */
export const TERMS = {
  space: 'Space',
  verifiedSpace: 'Verified space',
  unverifiedSpace: 'Unverified space',
  owner: 'Owner',
  spaceManagerLink: 'Space manager link',
  reception: 'Reception',
  frontDesk: 'Front desk',
  customer: 'Customer',
  visit: 'Visit',
  subscription: 'Subscription',
  package: 'Package',
  customSubscription: 'Custom subscription',
  subscriptionStatus: 'Subscription status',
  subscriptionStatuses: {
    active: 'Active',
    endingSoon: 'Ending soon',
    expired: 'Expired',
  },
  payment: 'Payment',
  amountDue: 'Amount due',
  balance: 'Balance',
  credit: 'Credit',
  paymentStatus: 'Payment status',
  paymentStatuses: {
    paid: 'Paid',
    partlyPaid: 'Partly paid',
    unpaid: 'Unpaid',
  },
  voidPayment: 'Void a payment',
  shift: 'Shift',
  checkIn: 'Check-in',
  openCheckIn: 'Open check-in',
  autoCheckOut: 'Auto check-out',
  capacity: 'Capacity',
  liveStatus: 'Live status',
  liveStatuses: {
    available: 'Available',
    full: 'Full',
    closedNow: 'Closed now',
  },
  manualStateOverride: 'Manual state override',
  occupancy: 'Occupancy',
  announcement: 'Announcement',
  dataReport: 'Data report',
  stale: 'Stale',
  governorate: 'Governorate',
  area: 'Area',
  lookup: 'Lookup',
  auditLog: 'Audit log',
} as const;
